<a href="https://colab.research.google.com/github/isj0/DeepLearning/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [ ]:
# basic list

my_list = [[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
# numpy arrays

np1 = np.random.rand(3, 4)
np1

array([[0.9261691 , 0.77050519, 0.88691613, 0.66839928],
       [0.73553282, 0.03389235, 0.20650084, 0.68295211],
       [0.26579032, 0.77642547, 0.70988083, 0.47908512]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
# Tensors

tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 1.4545, -0.4983,  1.2347, -0.4527],
        [-0.4220,  0.6006, -1.1456,  0.5998],
        [-0.7752, -0.2394,  0.0231, -1.2591]])

In [ ]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9262, 0.7705, 0.8869, 0.6684],
        [0.7355, 0.0339, 0.2065, 0.6830],
        [0.2658, 0.7764, 0.7099, 0.4791]], dtype=torch.float64)

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_torch2 = my_torch2.reshape(5, -1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch7[7:]

tensor([7, 8, 9])

In [ ]:
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [ ]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [ ]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [ ]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a.add_(tensor_b)
tensor_a

tensor([11, 14, 17, 20])

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# Create a Model class that inherits nn.Module

class Model(nn.Module):
    # Input layer (4 feature of the Iris flower)
    # Hidden Layer1 (number of nuerons)
    # Hidden layer2 (number of nuerons)
    # output (3 class of iris flowers)
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)

    def forward(self, X):
        x = F.relu(self.fc1(X))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x


In [3]:
# requires_grad=True means we want PyTorch to compute gradients
x = torch.tensor([2.0], requires_grad=True)


In [4]:
# A simple function
y = x**3 + 2*x

In [5]:
# Backprop
y.backward()

print("dy/dx =", x.grad)

dy/dx = tensor([14.])


In [6]:
# Check GPU
print(torch.cuda.is_available())

# Create tensor on GPU
x = torch.tensor([1, 2, 3], device="cuda")
print(x)

# Move tensor from GPU to CPU
y = x.cpu()
print(y)


True
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3])


In [7]:
from torchvision import datasets, transforms

In [8]:
transform = transforms.ToTensor()

In [9]:
train_dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)

100%|██████████| 9.91M/9.91M [00:00<00:00, 17.9MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 481kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.43MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 8.60MB/s]


In [13]:
# print the number of examples in this dataset
print("Number of training samples:", len(train_dataset))

Number of training samples: 60000


In [14]:
image, label = train_dataset[0]

print("Image shape:", image.shape)
print("Label:", label)

Image shape: torch.Size([1, 28, 28])
Label: 5


In [15]:
from torch.utils.data import DataLoader

In [16]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [17]:
# get one batch from the data loader
images, labels = next(iter(train_loader))

print("Batch of images shape:", images.shape)
print("Batch of labels shape:", labels)

Batch of images shape: torch.Size([32, 1, 28, 28])
Batch of labels shape: tensor([9, 6, 3, 0, 5, 5, 0, 8, 6, 5, 8, 4, 2, 6, 7, 3, 6, 6, 2, 3, 1, 0, 7, 8,
        1, 7, 8, 5, 4, 0, 7, 3])


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [3]:
# Load the MNIST dataset

transform = transforms.ToTensor()

train_dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

100%|██████████| 9.91M/9.91M [00:00<00:00, 20.0MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 485kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.50MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 11.2MB/s]


In [4]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [7]:
# Step 1: Build a simple Neural Network
# DNN - fully connected network - Task A

class SimpleDNN(nn.Module):
    def __init__(self):
        super(SimpleDNN, self).__init__()
        self.fc1 = nn.Linear(28*28, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# create a simple model
model = SimpleDNN()
model.to(device)
print(model)


SimpleDNN(
  (fc1): Linear(in_features=784, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=10, bias=True)
  (relu): ReLU()
)


In [8]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [10]:
for epoch in range(3):
    model.train()
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward

        # update weights
        optimizer.step()

    # print
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

Epoch 1, Loss: 2.2990
Epoch 2, Loss: 2.3042
Epoch 3, Loss: 2.3007


In [11]:
# Evaluate Accuracy

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total
    print(f"Test Accuracy: {accuracy:.2f}%")


Test Accuracy: 10.18%
